// Mocks generated by Mockito 5.4.5 from annotations
// in elevate_intake2_intro/test/ui/home/HomeViewModel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:elevate_intake2_intro/domain/common/Result.dart' as _i6;
import 'package:elevate_intake2_intro/domain/contracts/category/brands_repo.dart'
    as _i2;
import 'package:elevate_intake2_intro/domain/contracts/category/categories_repo.dart'
    as _i3;
import 'package:elevate_intake2_intro/domain/model/Brand.dart' as _i7;
import 'package:elevate_intake2_intro/domain/model/category.dart' as _i10;
import 'package:elevate_intake2_intro/domain/usecase/get_brands_use_case.dart'
    as _i4;
import 'package:elevate_intake2_intro/domain/usecase/get_categories_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBrandsRepo_0 extends _i1.SmartFake implements _i2.BrandsRepo {
  _FakeBrandsRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoriesRepo_1 extends _i1.SmartFake
    implements _i3.CategoriesRepo {
  _FakeCategoriesRepo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetBrandsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBrandsUseCase extends _i1.Mock implements _i4.GetBrandsUseCase {
  MockGetBrandsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BrandsRepo get brandsRepo => (super.noSuchMethod(
        Invocation.getter(#brandsRepo),
        returnValue: _FakeBrandsRepo_0(
          this,
          Invocation.getter(#brandsRepo),
        ),
      ) as _i2.BrandsRepo);

  @override
  set brandsRepo(_i2.BrandsRepo? _brandsRepo) => super.noSuchMethod(
        Invocation.setter(
          #brandsRepo,
          _brandsRepo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.Result<List<_i7.Brand>?>> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.Brand>?>>.value(
            _i8.dummyValue<_i6.Result<List<_i7.Brand>?>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.Brand>?>>);
}

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i9.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CategoriesRepo get categoriesRepo => (super.noSuchMethod(
        Invocation.getter(#categoriesRepo),
        returnValue: _FakeCategoriesRepo_1(
          this,
          Invocation.getter(#categoriesRepo),
        ),
      ) as _i3.CategoriesRepo);

  @override
  set categoriesRepo(_i3.CategoriesRepo? _categoriesRepo) => super.noSuchMethod(
        Invocation.setter(
          #categoriesRepo,
          _categoriesRepo,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.Result<List<_i10.Category>>> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i10.Category>>>.value(
            _i8.dummyValue<_i6.Result<List<_i10.Category>>>(
          this,
          Invocation.method(
            #invoke,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i10.Category>>>);
}
