// Mocks generated by Mockito 5.4.5 from annotations
// in elevate_intake2_intro/test/api/datasourceimpl/categories/CategoriesOnlineDatasourceImpl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:elevate_intake2_intro/api/model/response/brand/brands_response.dart'
    as _i3;
import 'package:elevate_intake2_intro/api/model/response/category/CategoriesResponse.dart'
    as _i2;
import 'package:elevate_intake2_intro/api/webServices/WebServices.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.CategoriesResponse {
  _FakeCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBrandsResponse_1 extends _i1.SmartFake
    implements _i3.BrandsResponse {
  _FakeBrandsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WebServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebServices extends _i1.Mock implements _i4.WebServices {
  MockWebServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CategoriesResponse> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i5.Future<_i2.CategoriesResponse>.value(_FakeCategoriesResponse_0(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i5.Future<_i2.CategoriesResponse>);

  @override
  _i5.Future<_i3.BrandsResponse> getBrands() => (super.noSuchMethod(
        Invocation.method(
          #getBrands,
          [],
        ),
        returnValue: _i5.Future<_i3.BrandsResponse>.value(_FakeBrandsResponse_1(
          this,
          Invocation.method(
            #getBrands,
            [],
          ),
        )),
      ) as _i5.Future<_i3.BrandsResponse>);
}
